### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by jwunderl** [AqeeAqee/pxt-raycasting#6]
To be counted as an approved extension we require MIT license -- if you add a LICENSE file from github it should give you an option to fill it in automatically, here's an example of one that is generated:

https://github.com/jwunderl/pxt-status-bar/blob/master/LICENSE

if you click 'add new file' in github it'll look like this when the name is set to license:

![image](https://user-images.githubusercontent.com/5615930/170143261-8f4ffff2-62bc-4ee5-bd77-d2e294448204.png)

where you can click the top right corner 'Choose a license template' to get help adding the mit license

**Comment by jwunderl** [comment]
This was added 🎊🎊🎆✨💖

**Comment by AqeeAqee** [comment]
Done
https://github.com/AqeeAqee/pxt-raycasting/blob/master/LICENSE
